#GNU make install directory path: 
export GNUMakeInstallDirPath=

#Project directory path: 
export ProjDirPath=/cygdrive/d/workspace/C_interpreter/iArduino

#Make directory path: 
export MakeDirPath=/cygdrive/d/workspace/C_interpreter/iArduino

#Make resources directory path: 
export MakeResDirPath=./resources

#Make sources directory path: 
export MakeSrcDirPath=./sources

#Make output directory path: 
export MakeOutDirPath=./out
